/**
 * Search Result Types
 * Domain types for search results, pain points, quotes, and AI analysis
 */

import type { HNTag, TimeRange, SortBy, SearchStatus } from "./database";

/**
 * Pain point identified from HN discussions
 */
export interface PainPoint {
  id: string;
  searchId: string;
  title: string;
  sourceTag: string;
  mentionsCount: number;
  severityScore?: number;
}

/**
 * Quote supporting a pain point
 */
export interface PainPointQuote {
  id: string;
  painPointId: string;
  quoteText: string;
  authorHandle: string | null;
  upvotes: number;
  permalink: string;
}

/**
 * Problem cluster from Gemini AI analysis
 */
export interface ProblemCluster {
  title: string;
  description: string;
  severity: number;
  mentionCount: number;
  examples: string[];
}

/**
 * Product idea generated by AI
 */
export interface ProductIdea {
  title: string;
  description: string;
  targetProblem: string;
  impactScore: number;
}

/**
 * Complete AI analysis response
 */
export interface AiAnalysis {
  summary: string;
  problemClusters: ProblemCluster[];
  productIdeas: ProductIdea[];
  model?: string;
  tokensUsed?: number;
}

/**
 * Full assembled search result returned by API and stored in cache
 */
export interface SearchResult {
  searchId: string;
  status: SearchStatus;
  topic: string;
  tags: HNTag[];
  timeRange: TimeRange;
  minUpvotes: number;
  sortBy: SortBy;
  totalMentions?: number;
  totalPostsConsidered?: number;
  totalCommentsConsidered?: number;
  sourceTags?: string[];
  painPoints: PainPoint[];
  quotes: PainPointQuote[];
  analysis?: AiAnalysis;
  errorMessage?: string;
}

/**
 * UI-friendly search result item (transformed for frontend display)
 */
export interface SearchResultItem {
  id: number;
  painTitle: string;
  mentions: number;
  tag: string;
  quotes: Array<{
    text: string;
    upvotes: number;
    author: string;
    permalink?: string;
  }>;
}
